### ISSUE TITLE
Show Error on the first screen 

### ISSUE THREAD

**Issue by harshilchovatiya** [suleymangunes/TradingView-app#2]
When I open the app at that time it's show the error and in the console is show this
[log] Instance of 'CryptoCubit', Change { currentState: Instance of 'CryptoInitial', nextState: Instance of 'CryptoLoading' }
[log] Instance of 'CryptoCubit', Change { currentState: Instance of 'CryptoLoading', nextState: Instance of 'CryptoError' }

Nothing any things else

![image](https://github.com/user-attachments/assets/24b8b536-83d1-4947-89bb-c259a26baf78)

**Comment by workspace-cs** [comment]
Did you integrate the coinmarketcap key mentioned in the readme usage section into the code?
